# ------------------------------------------------------------------------------
# ~/.bashrc
#
# Interactive Bash configuration.
#
# This file is executed for interactive Bash shells and defines:
#   - prompt (PS1/PS2)
#   - aliases
#   - readline key bindings
#   - completion
#   - tmux auto-start
#
# It assumes the environment has already been set up by ~/.bash_profile.
# Non-interactive shells return immediately.
#
# ------------------------------------------------------------------------------

# ---- interactive shell only!
[[ $- != *i* ]] && return

# ---- tmux auto-start, without exec (so we can exit without closing)
if [[ -z $TMUX ]]; then
    tmux has-session 2> /dev/null
    if (( $? )); then
        tmux new -s Session
    else
        tmux attach
    fi
fi

# ---- Source aliases
if [[ -f ~/.bash_aliases ]]; then
    source ~/.bash_aliases
fi

# ---- bash completion
if [[ -f /opt/homebrew/etc/bash_completion ]]; then
    source /opt/homebrew/etc/bash_completion
fi

# ---- git prompt addition
if [[ -f /opt/homebrew/etc/bash_completion.d/git-prompt.sh ]]; then
    source /opt/homebrew/etc/bash_completion.d/git-prompt.sh
fi

export CLICOLOR=1
export LSCOLORS=exGxBxDxCxEgEdxbxgxcxd # man ls /LSCOLORS

# ---- prompt
# Kanagawa-inspired colors
C_CUR='\[\e[38;5;107m\]'   # springGreen
C_PATH='\[\e[38;5;110m\]'  # crystalBlue
C_USER='\[\e[38;5;167m\]'  # waveRed
C_RST='\[\e[0m\]'

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWCOLORHINTS=1

PS1="${C_USER}&rea§:${C_PATH}\W/${C_RST}\$(__git_ps1 ' (%s)')${C_CUR}>_ ${C_RST} "
PS2="${C_CUR}\$ ${C_RST}"

export MANPAGER="nvim +Man!"
# export MANPAGER="less -R --use-color \
#   -Dd+203 \
#   -Du+75  \
#   -DS+203 \
#   -DP+110 \
#   -DE+203 \
#   -DN+173"

# ---- readline
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind 'set completion-ignore-case on'
bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'
bind '"\C-x\C-e": edit-and-execute-command'

# ---- shell options --- help shopt, man bash under builtins
shopt -s autocd
shopt -s direxpand
