alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias uio='cd ~/Documents/UIO/02_master/8_semester'
alias movies='cd ~/Movies'
alias downloads='cd ~/Downloads'
alias c='clear'
alias ta='uio && cd TA'
alias new=':>'

alias srcsh='source ~/.bashrc'
alias edit='nvim ~/.bashrc'
alias aliases='nvim ~/.bash_aliases'
alias vim=nvim

alias ll='ls -l'
alias la='ls -Aohp'
alias l.='ls -dp .*'
alias ll.='ls -dlp .*'

alias cat='bat -p'
alias please='sudo $(fc -ln -1)'
alias grep='grep --color=auto'
alias weather='curl wttr.in'
alias ghidra='/opt/homebrew/Cellar/ghidra/12.0/libexec/ghidraRun'

# Setting the default pager for man pages
alias less="less -R --use-color \
  -Dd+203 \
  -Du+75  \
  -DS+203 \
  -DP+110 \
  -DE+203 \
  -DN+173"
############# in3000 sshfs specific.
alias mount_in3000='sshfs ifi:in3000 ~/dev/in3000 \
-o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3 \
-o defer_permissions \
-o ssh_command="ssh -o ControlMaster=no -o ControlPath=none -o TCPKeepAlive=no"'
alias unmount_in3000='umount -f ~/dev/in3000'
####################################

# Find
alias f='find . -iname'

# Safe operations
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# Directory creation and enter
md() { 
    if [[ -z "$1" ]]; then
        printf "[Error] You have to give a name\n\tmd <dirname>\n"
        return 1
    fi
    mkdir -p "$1" && cd "$1"; 
}

commas() {
    local num="$1"
    local result=""
    local sign=""

    # Handle negative numbers
    if [[ $num == -* ]]; then
        sign="-"
        num="${num#-}"
    fi

    while [[ ${#num} -gt 3 ]]; do
        result=",$(printf '%s' "${num: -3}")$result"
        num="${num:0:${#num}-3}"
    done

    printf "%s%s%s\n" "$sign" "$num" "$result"
}

seconds() {
    local T=$1
    local D=$((T/86400))
    local H=$((T/3600%24))
    local M=$((T/60%60))
    local S=$((T%60))

    (( D > 0 )) && printf '%d days ' "$D"
    (( H > 0 )) && printf '%d hours ' "$H"
    (( M > 0 )) && printf '%d minutes ' "$M"
    (( D > 0 || H > 0 || M > 0 )) && printf 'and '
    printf '%d seconds\n' "$S"
}

degrees() {
    local value=$1
    local celsius=0

    [[ "$2" == "-c" ]] && celsius=1

    if (( celsius )); then
        local F=$(( value * 1.8 + 32 ))
        printf '%.1f°C is %.1f°F\n' "$value" "$F"
    else
        local C=$(( (value - 32) / 1.8 ))
        printf '%.1f°F is %.1f°C\n' "$value" "$C"
    fi
}
